/* tslint:disable */
/* eslint-disable */
/*
 * Globalize Culture fr-FR
 *
 * http://github.com/jquery/globalize
 *
 * Copyright Software Freedom Conservancy, Inc.
 * Dual licensed under the MIT or GPL Version 2 licenses.
 * http://jquery.org/license
 *
 * This file was generated by the Globalize Culture Generator
 * Translation: bugs found in this file need to be fixed in the generator
 */

(function( window, undefined ) {

var Globalize;

if ( typeof require !== "undefined" &&
	typeof exports !== "undefined" &&
	typeof module !== "undefined" ) {
	// Assume CommonJS
	Globalize = require( "globalize" );
} else {
	// Global variable
	Globalize = window.Globalize;
}

Globalize.addCultureInfo( "vi-VN", "default", {
	name: "vi-VN",
	englishName: "Vietnam (VietNam)",
	nativeName: "Vietnam (VietNam)",
	language: "vi",
	calendars: {
		standard: {
			firstDay: 1,
			days: {
				names: ["CN","T2","T3","T4","T5","T6","T7"],
				namesAbbr: ["CN","T2","T3","T4","T5","T6","T7"],
				namesShort: ["CN","T2","T3","T4","T5","T6","T7"]
			},
			months: {
				names: ["Tháng 1","Tháng 2","Tháng 3","Tháng 4","Tháng 5","Tháng 6","Tháng 7","Tháng 8","Tháng 9","Tháng 10","Tháng 11","Tháng 12",""],
				namesAbbr: ["Tháng 1","Tháng 2","Tháng 3","Tháng 4","Tháng 5","Tháng 6","Tháng 7","Tháng 8","Tháng 9","Tháng 10","Tháng 11","Tháng 12",""]
			}
		}
	}
});

}( this ));
